### ISSUE TITLE
AAAA EBADSIGNATURE on google.com

### ISSUE THREAD

**Issue by realrasengan** [handshake-org/hdns#1]
Running this code:

```
const dns = require('hdns');

(async function() {
  console.log(await dns.lookup('google.com', { all: true }));
})();

```
Yields the following error:

```
 (node:2258) UnhandledPromiseRejectionWarning: Error: queryAAAA EBADSIGNATURE google.com
     at makeError (/home/rasengan/node_modules/bns/lib/api.js:832:15)
     at makeQueryError (/home/rasengan/node_modules/bns/lib/api.js:842:10)
     at API._ask (/home/rasengan/node_modules/bns/lib/api.js:137:17)
     at <anonymous>
     at process._tickCallback (internal/process/next_tick.js:188:7)
 (node:2258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
 (node:2258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pinheadmz** [comment]
`queryAAAA` -- without digging in, my first reaction is that your ISP doesn't support ipv6?

see https://github.com/bcoin-org/bdns/issues/1

**Comment by realrasengan** [comment]
I do have IPv6!

```
$ ping -c 4 2607:f8b0:4005:804::200e
PING 2607:f8b0:4005:804::200e(2607:f8b0:4005:804::200e) 56 data bytes
64 bytes from 2607:f8b0:4005:804::200e: icmp_seq=1 ttl=51 time=61.5 ms
64 bytes from 2607:f8b0:4005:804::200e: icmp_seq=2 ttl=51 time=61.5 ms
64 bytes from 2607:f8b0:4005:804::200e: icmp_seq=3 ttl=51 time=61.7 ms
64 bytes from 2607:f8b0:4005:804::200e: icmp_seq=4 ttl=51 time=61.7 ms

--- 2607:f8b0:4005:804::200e ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 61.580/61.668/61.797/0.317 ms
```

Do I need to do anything else special (i.e., run hsd locally or otherwise)?
(Note: The /etc/resolv.conf is pointing at an IP which is running a hsd resolver on port 53!)

**Comment by publiusfederalist** [comment]
EBADSIGNATURE is a result of the NS servers supplying incorrect identity keys.  I also encountered separate timeout issues due to servers being unreachable.  This is addressed in PR https://github.com/handshake-org/hdns/pull/2 with new default NS supplied in the resolvconf.
